const TOP_CENTER = { x: 176.3, y: 177.318 };
const BOTTOM_CENTER = { x: 176.3, y: 477.318 };
const DRAG_SPEED_MODIFIER = 0.5;
const DEGREE_COLLISION_MODIFIER = 18;
const DEGREE_CONSTRAINTS = { min: -90, max: 90 };
const SLIDING_RANGE = 180;

export {
  TOP_CENTER,
  BOTTOM_CENTER,
  DRAG_SPEED_MODIFIER,
  DEGREE_CONSTRAINTS,
  DEGREE_COLLISION_MODIFIER,
  SLIDING_RANGE,
};
